"""reporting

Revision ID: d_001
Revises: d_000
Create Date: 2026-08-17 18:33:23.448980
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d_001"
down_revision: str | Sequence[str] | None = "d_000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_manifests",
        sa.Column("manifest_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("deletion_request_id", sa.String(length=36), nullable=False),
        sa.Column("manifest_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("manifest_id", name=op.f("pk_deletion_manifests")),
    )
    op.create_index(
        op.f("ix_deletion_manifests_company_id"), "deletion_manifests", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_deletion_manifests_deletion_request_id"),
        "deletion_manifests",
        ["deletion_request_id"],
        unique=False,
    )
    op.create_table(
        "deletion_requests",
        sa.Column("deletion_request_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("applicant_id", sa.String(length=36), nullable=False),
        sa.Column("invitation_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("policy_snapshot", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("deletion_request_id", name=op.f("pk_deletion_requests")),
    )
    op.create_index(
        op.f("ix_deletion_requests_company_id"), "deletion_requests", ["company_id"], unique=False
    )
    op.create_table(
        "deletion_targets",
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("manifest_id", sa.String(length=36), nullable=False),
        sa.Column("store", sa.String(length=32), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("owner_lane", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=128), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("target_id", name=op.f("pk_deletion_targets")),
    )
    op.create_index(
        op.f("ix_deletion_targets_company_id"), "deletion_targets", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_deletion_targets_manifest_id"), "deletion_targets", ["manifest_id"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("report_item_id", sa.String(length=36), nullable=False),
        sa.Column("criterion_id", sa.String(length=36), nullable=False),
        sa.Column("competency_model_version_id", sa.String(length=36), nullable=False),
        sa.Column("answer_turn_id", sa.String(length=36), nullable=False),
        sa.Column("transcript_segment_id", sa.String(length=36), nullable=False),
        sa.Column("video_start_ms", sa.Integer(), nullable=False),
        sa.Column("video_end_ms", sa.Integer(), nullable=False),
        sa.Column("observation", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("sufficiency", sa.String(length=32), nullable=False),
        sa.Column("generation_version", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("evidence_id", name=op.f("pk_evidence")),
    )
    op.create_index(op.f("ix_evidence_company_id"), "evidence", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_report_item_id"), "evidence", ["report_item_id"], unique=False
    )
    op.create_table(
        "human_reviews",
        sa.Column("human_review_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("company_user_id", sa.String(length=36), nullable=False),
        sa.Column("review_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("human_review_id", name=op.f("pk_human_reviews")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_human_reviews_idempotency_key")),
    )
    op.create_index(
        op.f("ix_human_reviews_company_id"), "human_reviews", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_reviews_report_id"), "human_reviews", ["report_id"], unique=False
    )
    op.create_table(
        "recording_assets",
        sa.Column("recording_asset_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("interview_session_id", sa.String(length=36), nullable=False),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("missing_ranges", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("recording_asset_id", name=op.f("pk_recording_assets")),
    )
    op.create_index(
        op.f("ix_recording_assets_company_id"), "recording_assets", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_recording_assets_interview_session_id"),
        "recording_assets",
        ["interview_session_id"],
        unique=False,
    )
    op.create_table(
        "report_items",
        sa.Column("report_item_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("criterion_id", sa.String(length=36), nullable=False),
        sa.Column("competency_model_version_id", sa.String(length=36), nullable=False),
        sa.Column("assessment_state", sa.String(length=32), nullable=False),
        sa.Column("observation", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("uncertainty", sa.Text(), nullable=False),
        sa.Column("follow_up_question", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("report_item_id", name=op.f("pk_report_items")),
    )
    op.create_index(
        op.f("ix_report_items_company_id"), "report_items", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_report_items_report_id"), "report_items", ["report_id"], unique=False)
    op.create_table(
        "reporting_session_events",
        sa.Column("session_event_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("interview_session_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("session_start_ms", sa.Integer(), nullable=False),
        sa.Column("session_end_ms", sa.Integer(), nullable=False),
        sa.Column("technical_failure", sa.Boolean(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("session_event_id", name=op.f("pk_reporting_session_events")),
    )
    op.create_index(
        op.f("ix_reporting_session_events_company_id"),
        "reporting_session_events",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reporting_session_events_interview_session_id"),
        "reporting_session_events",
        ["interview_session_id"],
        unique=False,
    )
    op.create_table(
        "reports",
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("interview_session_id", sa.String(length=36), nullable=False),
        sa.Column("competency_model_version_id", sa.String(length=36), nullable=False),
        sa.Column("report_version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("model_config_version", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("report_id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_company_id"), "reports", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_reports_interview_session_id"), "reports", ["interview_session_id"], unique=False
    )
    op.create_table(
        "transcript_segments",
        sa.Column("transcript_segment_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("interview_session_id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("speaker", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("session_start_ms", sa.Integer(), nullable=False),
        sa.Column("session_end_ms", sa.Integer(), nullable=False),
        sa.Column("source_audio_key", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("corrected_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("transcript_segment_id", name=op.f("pk_transcript_segments")),
    )
    op.create_index(
        op.f("ix_transcript_segments_company_id"),
        "transcript_segments",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_segments_interview_session_id"),
        "transcript_segments",
        ["interview_session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transcript_segments_interview_session_id"), table_name="transcript_segments"
    )
    op.drop_index(op.f("ix_transcript_segments_company_id"), table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_index(op.f("ix_reports_interview_session_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_company_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(
        op.f("ix_reporting_session_events_interview_session_id"),
        table_name="reporting_session_events",
    )
    op.drop_index(
        op.f("ix_reporting_session_events_company_id"), table_name="reporting_session_events"
    )
    op.drop_table("reporting_session_events")
    op.drop_index(op.f("ix_report_items_report_id"), table_name="report_items")
    op.drop_index(op.f("ix_report_items_company_id"), table_name="report_items")
    op.drop_table("report_items")
    op.drop_index(op.f("ix_recording_assets_interview_session_id"), table_name="recording_assets")
    op.drop_index(op.f("ix_recording_assets_company_id"), table_name="recording_assets")
    op.drop_table("recording_assets")
    op.drop_index(op.f("ix_human_reviews_report_id"), table_name="human_reviews")
    op.drop_index(op.f("ix_human_reviews_company_id"), table_name="human_reviews")
    op.drop_table("human_reviews")
    op.drop_index(op.f("ix_evidence_report_item_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_company_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_deletion_targets_manifest_id"), table_name="deletion_targets")
    op.drop_index(op.f("ix_deletion_targets_company_id"), table_name="deletion_targets")
    op.drop_table("deletion_targets")
    op.drop_index(op.f("ix_deletion_requests_company_id"), table_name="deletion_requests")
    op.drop_table("deletion_requests")
    op.drop_index(
        op.f("ix_deletion_manifests_deletion_request_id"), table_name="deletion_manifests"
    )
    op.drop_index(op.f("ix_deletion_manifests_company_id"), table_name="deletion_manifests")
    op.drop_table("deletion_manifests")
    # ### end Alembic commands ###
